@startuml
actor Socio
actor Biblioteca

rectangle {
  Socio --> (Reservar Libro)
  Socio --> (Prestar Libro)
  Socio --> (Devolver Libro)
  Biblioteca --> (Actualizar Catálogo)
   Biblioteca --> (Prestar Libro)

}
@enduml