@startuml
actor Agente


  Agente --> (Evaluar Solicitud de Crédito)
  (Enviar Solicitud de Crédito Empresarial) --> (Evaluar Solicitud de Crédito)
    (Enviar Solicitud de Crédito Personal) --> (Evaluar Solicitud de Crédito)




@enduml